<?php
/**
 * Copyright © WebePower LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.webepower.biz | support@webepower.biz
 */

/** @var $block Webepower\GoogleTagManager\Block\GtmBlock **/
?>

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?= /* @noEscape */ $block->getAccountId() ?>"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->